### ISSUE TITLE
Make the server stoppable

### ISSUE THREAD

**Issue by schlenger** [collective-soundworks/soundworks#15]
I got the following case: I run soundworks in an environment where I use test cases. I can start the server within this environment, but I haven't found an option to stop it, which leads to an endless running test which has to be force quit.

It would be nice to have a function exposed which offers the stop task of the server to provide a better interface from the outside. This could also be helpful, if soundworks is embedded as a sub service within a bigger installation.

**Comment by b-ma** [comment]
Yes that's a good point, I think such functionality could also be very helpful for some client-side use cases.

To be honest, I won't dig into that with soundworks#v2, and I guess the quick and dirty way right now is to kill the process programmatically when your tests are done (i.e. using `process.exit` or `process.kill`).

However that's something which is definitely in the todo list for the v3, while I can't give any deadline for that as I first have to release this version properly. Also as soundworks clients and server are now (in v3) instances instead of POJO singletons it should be more easy to implement and much more consistent.

Let's keep this open as a reminder !

**Comment by schlenger** [comment]
Yes, Mocha e.g. supports this with the `--exit` flag (if anyone else needs this), which is working for this. 
This was also more an idea for v3. Thanks

**Comment by b-ma** [comment]
Added `await server.close()` in v3.3.0 (Finally...)

**Comment by schlenger** [comment]
Nice job @b-ma! Thanks for letting me know and keep up the good work
