### ISSUE TITLE
More than one OSC destination?

### ISSUE THREAD

**Issue by MAOShea** [collective-soundworks/soundworks#5]
Hi Guys,

until now I have used server.osc.send() to send messages to one OSC destination and that works fine.

What do you recommend I do in order to send messages to 2 destinations? I would send certain message types to one destination (the video server, for example) and certain messages types to the other (a MAX/MSP master controller, for example).

Should I instantiate my own separate OSC session (i.e. not passing through the one offered by the server class)?

Or is there a clever way of using server.osc to achieve the desired result?

Regards,

Michael

**Comment by b-ma** [comment]
Hi,

Can you tell me which version of soundworks you are using because `server.osc.send` no longer exists since a while?

In the 1.x.x version you can send an osc message (using the `osc` service) to multiple destinations by using the full signature of the `send` method:

```js
this.osc = this.require('osc');
// later
this.osc.send(address, args, ip, port);
```

With an earlier version, if I remember well it is possible too but it has to be verified.

Cheers,

**Comment by MAOShea** [comment]
I'm on 1.0.2 or something (quoting from memory). I've been putting off
upgrading, focussing on stabilising my own implementation.

You say that you have removed osc from server? Have you built an
alternative or are you leaving it to the user to manage OSC comms
themselves?

Thanks for the answers so far!

Michael

**Comment by b-ma** [comment]
Hey Michael,

Since v1 osc is accessible as a service of the server side experience as describe here http://collective-soundworks.github.io/soundworks/module-soundworks_server.Osc.html. So, it should be possible to communicate with several destinations by setting the optional `url` (badly named, should be `ip`) and `port` arguments of the `send` method.

To make the thing work, you (more or less) have to:

- configure the default destination in the server
```js
soundworks.server.init({
  osc: {
    receiveAddress: '10.0.0.1',
    receivePort: 57121,
    sendAddress: '10.0.0.1',
    sendPort: 57120,
  },
});
```

- require the service in the `Experience` constructor: 
```js
this.osc = this.require('osc');
```

- send messages once the `Experience` has started:
```js
this.osc.send('/channel/video', [0, 1, 2], '10.0.0.2', 57121);
this.osc.send('/channel/max', [3, 4, 5], '10.0.0.3', 57121);
```

Cheers,
Benjamin

**Comment by MAOShea** [comment]
Awesome. I love you.

M
